version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: geofence_db
      POSTGRES_USER: geofence_user
      POSTGRES_PASSWORD: geofence_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/sample_data.sql:/docker-entrypoint-initdb.d/sample_data.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  geofence-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://geofence_user:geofence_pass@postgres:5432/geofence_db
      REDIS_URL: redis://redis:6379
      DEBUG: "true"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data: